# Generated by Django 5.1 on 2024-09-06 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todomodel_deedate_todomodel_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='deedate',
            new_name='duedate',
        ),
    ]
